### ISSUE TITLE
How to use it on my project ?

### ISSUE THREAD

**Issue by arnaudforaison** [peruvianidol/coolcss#1]
Hello, great article & great job for coolcss

I would like to test ou last css framework but how i can use it on my side ?

**Comment by peruvianidol** [comment]
Thanks, Arnaud. If you clone or fork the repo, and follow the directions in the readme to run Eleventy, Eleventy will convert the files in the `_src` folder to a new folder called `_site`. In that folder you'll find `css/cool.css`. You can use that file in your project, or if you'd like to customize the prefix or design tokens, you can do so in `_src/sass/abstracts/_tokens.scss` and Eleventy will compile your changes into cool.css.

I'll try to add some more documentation around this soon. Everything is still in the early stages and you'll probably find a lot of things missing, but thanks for checking out cool.css and please let me know if you have any questions!

**Comment by arnaudforaison** [comment]
Thanks for you answer, I will test it soon.
